displayName=Vampyrium Rockslide
author=Brik
description=Tracks the cooldown on gaining XP from the Vampyrium rockslide shortcut
tags=vampyrium,agility
version=
plugins=com.vampyriumrockslide.VampyriumRockslidePlugin
build=standard